// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRAsc4RX5xm24IUQBEilDOjNOfBKbdhEM',
    appId: '1:317548141612:web:e36620148afccd081f0589',
    messagingSenderId: '317548141612',
    projectId: 'animooo',
    authDomain: 'animooo.firebaseapp.com',
    storageBucket: 'animooo.firebasestorage.app',
    measurementId: 'G-WMFVTXX4T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq5Tjwx07Ebr62UnddwZPfgnilkc-cEOQ',
    appId: '1:317548141612:android:392e88109ceb59541f0589',
    messagingSenderId: '317548141612',
    projectId: 'animooo',
    storageBucket: 'animooo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoyudXLEmxp7DPtn1v9b9Fl6gMRPg7yYw',
    appId: '1:317548141612:ios:6a940b68a2ae18011f0589',
    messagingSenderId: '317548141612',
    projectId: 'animooo',
    storageBucket: 'animooo.firebasestorage.app',
    iosBundleId: 'com.example.amimooo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoyudXLEmxp7DPtn1v9b9Fl6gMRPg7yYw',
    appId: '1:317548141612:ios:6a940b68a2ae18011f0589',
    messagingSenderId: '317548141612',
    projectId: 'animooo',
    storageBucket: 'animooo.firebasestorage.app',
    iosBundleId: 'com.example.amimooo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRAsc4RX5xm24IUQBEilDOjNOfBKbdhEM',
    appId: '1:317548141612:web:8a40e1bbacede4ef1f0589',
    messagingSenderId: '317548141612',
    projectId: 'animooo',
    authDomain: 'animooo.firebaseapp.com',
    storageBucket: 'animooo.firebasestorage.app',
    measurementId: 'G-CWFP7NCWH5',
  );
}
